name: Codacy Analysis CLI

on: ["push"]

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: macos-10.15
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
