name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  swift:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-11.0, macos-10.5]

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: swift build -v
    - name: run tests
      run: swift test -v
